<?php
declare(strict_types=1);
$isSlotEdit = is_array($slotForm);
$slotAction = $isSlotEdit ? '/admin/staffing/slots/update.php' : '/admin/staffing/slots/create.php';
$selectedVus = [];
if ($isSlotEdit) {
    try { $selectedVus = staffing_repository()->slot($registerId, (int) $selectedVersion['id'], (int) $slotForm['id'])['vus_requirements']; } catch (Throwable) { $selectedVus = []; }
}
?>
<form method="post" action="<?= e($slotAction) ?>" class="organization-form-grid">
    <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="register_id" value="<?= $registerId ?>"><input type="hidden" name="version_id" value="<?= (int) $selectedVersion['id'] ?>"><input type="hidden" name="expected_revision" value="<?= (int) $selectedVersion['revision'] ?>"><?php if ($isSlotEdit): ?><input type="hidden" name="slot_id" value="<?= (int) $slotForm['id'] ?>"><?php endif; ?>
    <label class="span-2">Организационный элемент<select name="organizational_structure_element_id" required><?php foreach ($nodes as $entry): $node=$entry['node']; ?><option value="<?= (int) $node['organizational_structure_element_id'] ?>" <?= (int) ($slotForm['organizational_structure_element_id'] ?? 0) === (int) $node['organizational_structure_element_id'] ? 'selected' : '' ?>><?= e(str_repeat('— ', (int) $entry['depth']) . (string) $node['name'] . ' · ' . (string) $node['type_name']) ?></option><?php endforeach; ?></select></label>
    <label>Тип должности<select name="position_type_id" required><?php foreach ($positionTypes as $type): ?><option value="<?= (int) $type['id'] ?>" <?= (int) ($slotForm['position_type_id'] ?? 0) === (int) $type['id'] ? 'selected' : '' ?>><?= e((string) $type['name']) ?></option><?php endforeach; ?></select></label>
    <label>Вариант<select name="position_variant_id"><option value="">Не выбран</option><?php foreach ($positionVariants as $variant): ?><option value="<?= (int) $variant['id'] ?>" <?= (int) ($slotForm['position_variant_id'] ?? 0) === (int) $variant['id'] ? 'selected' : '' ?>><?= e((string) $variant['designation']) ?></option><?php endforeach; ?></select></label>
    <label>Внутренний код<input name="internal_code" maxlength="64" value="<?= e((string) ($slotForm['internal_code'] ?? '')) ?>"></label><label>Наименование<input name="display_name" maxlength="255" value="<?= e((string) ($slotForm['display_name'] ?? '')) ?>" required></label>
    <?php foreach (['minimum_rank_id'=>'Минимальное звание','maximum_rank_id'=>'Максимальное звание','preferred_rank_id'=>'Предпочтительное звание'] as $field=>$label): ?><label><?= e($label) ?><select name="<?= e($field) ?>"><option value="">Не задано</option><?php foreach ($ranks as $rank): ?><option value="<?= (int) $rank['id'] ?>" <?= (int) ($slotForm[$field] ?? 0) === (int) $rank['id'] ? 'selected' : '' ?>><?= e((string) $rank['troop_name']) ?></option><?php endforeach; ?></select></label><?php endforeach; ?>
    <label>Нормативное состояние<select name="normative_state"><?php foreach (['active'=>'Действует','suspended'=>'Приостановлена','closed'=>'Закрыта'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($slotForm['normative_state'] ?? 'active') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Порядок<input type="number" min="1" name="sort_order" value="<?= (int) ($slotForm['sort_order'] ?? (count($slots)+1)) ?>" required></label>
    <fieldset class="span-2"><legend>Публичные требования ВУС (до трех)</legend><?php for ($i=0;$i<3;$i++): $req=$selectedVus[$i]??null; ?><div class="organization-inline-form"><select name="vus_id[]"><option value="">Не выбрано</option><?php foreach ($vusDisclosures as $vus): ?><option value="<?= (int) $vus['id'] ?>" <?= is_array($req) && (int) $req['public_disclosure_id'] === (int) $vus['id'] ? 'selected' : '' ?>><?= e((string) ($vus['raw_identifier'] ?: $vus['qualification_name'] ?: $vus['code'])) ?></option><?php endforeach; ?></select><select name="vus_role[]"><?php foreach (['required'=>'Требуется','allowed'=>'Допускается','preferred'=>'Предпочтительно'] as $value=>$label): ?><option value="<?= $value ?>" <?= is_array($req) && $req['requirement_role'] === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><?php endfor; ?></fieldset>
    <label class="span-2">Примечание<textarea name="note" maxlength="5000"><?= e((string) ($slotForm['note'] ?? '')) ?></textarea></label><div class="span-2 organization-actions"><button class="primary-button" type="submit"><?= $isSlotEdit ? 'Сохранить позицию' : 'Добавить позицию' ?></button></div>
</form>
