-- Canonical SQL is generated by MilitaryRankDirectoryV2MigrationCompatibility.php.
-- The marker below must never execute when the compatibility loader is wired correctly.
ASU_VCH_MILITARY_RANKS_V2_COMPATIBILITY_LOADER_REQUIRED;
